on:
 schedule:
    - cron: '0 0 * * *' # This runs daily at midnight
 workflow_dispatch:

jobs:
 update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for new Floorp releases
        id: check_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/Floorp-Projects/Floorp/releases/latest | jq -r '.tag_name')
          if [ -n "$latest_release" ]; then
            echo "::set-output name=latest_release::$latest_release"
            echo "latest release: $latest_release"
          fi

      #- name: Update _service and floorp-brower-nosrc.spec
      #  if: steps.check_release.outputs.latest_release != ''
      #  run: |
      #    # Replace the placeholder with the actual logic to update the files
      #    echo "Updating _service and floorp-brower-nosrc.spec with the new release URL"
      #    # You might need to use a script or a tool to update the files based on the latest release

      - name: Commit and push changes
        if: steps.check_release.outputs.latest_release != ''
        run: |
          git config --global user.name 'sounddrill31'
          git config --global user.email 'sounddrill31@gmail.com'
          git add .
          git commit -m "Update Floorp browser to latest release"
          git push
