name: Autoupdate Crave version
on:
  schedule:
     - cron: '0 0 */10 * *' # This runs every 10 days
  workflow_dispatch:

jobs:
  update:
     runs-on: ubuntu-latest
     steps: 
       - name: Checkout repository
         uses: actions/checkout@v4

       - name: Check for new Crave releases
         id: check_release
         run: |
          latest_release=$(curl -s https://api.github.com/repos/accupara/crave/releases/latest | jq -r '.tag_name')
          latest_release_no_v=$(echo $latest_release | sed 's/^v//')

          if [ ! -f latest_version.txt ]; then
            echo "$latest_release_no_v" > latest_version.txt
            echo "Created latest_version.txt with $latest_release"
          fi

          current_version=$(cat latest_version.txt)

          if [[ "$latest_release_no_v" > "$current_version" ]]; then
            echo "latest release: $latest_release"
            echo "latest_release=$latest_release" >> "$GITHUB_ENV"
            echo "$latest_release_no_v" > latest_version.txt
            echo "Updated latest_version.txt with $latest_release, triggering build..."
          else
            echo "No New Updates found"
            exit 1
          fi
       - name: Update _service and crave.spec
         run: |
          echo "Updating _service and crave.spec with the new release URL"
          echo "Doing changelog"
          CRAVE_BUILD_DATE=$(date "+%b %d %Y")
          echo "Build Date: $CRAVE_BUILD_DATE"
          CRAVE_BUILD_DAY=$(date "+%a")
          echo "Build Day: $CRAVE_BUILD_DAY"
          CRAVE_BUILD_YEAR=$(date "+%Y") 
          echo "Build Year: $CRAVE_BUILD_YEAR" 
          export CRAVE_VER=${latest_release}
          export CRAVE_VER_NO_V=$(echo $CRAVE_VER | sed 's/^v//')
          changelog_entry="* ${CRAVE_BUILD_DAY} ${CRAVE_BUILD_DATE} tex - ${CRAVE_VER_NO_V}-1pclos${CRAVE_BUILD_YEAR}"
          echo "$changelog_entry"
          if grep -q "$changelog_entry" crave.spec.example; then
            echo "Entry already exists, skipping"
          else
            sed -i "/%changelog/a $changelog_entry" crave.spec.example 
            sed -i "/$changelog_entry/a - new version\n" crave.spec.example
          fi           
          echo "Increment example changelog"
          git config --global user.name 'sounddrill31'
          git config --global user.email 'sounddrill31@gmail.com'
          git add .
          git commit -m "Update Crave to latest release"

          if [[ -n "${{ secrets.TESTING }}" ]]; then
            git push         
          fi

          echo "Using new version"
          envsubst < ${PWD}/crave.spec.example >> ${PWD}/crave.spec
          envsubst < ${PWD}/_service.example >> ${PWD}/_service
          rm _service.example crave.spec.example
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
       - name: Commit and push changes
         run: |
          git checkout -b $latest_release
          git config --global user.name 'sounddrill31'
          git config --global user.email 'sounddrill31@gmail.com'
          git add .
          git commit -m "Update Crave to latest release"
          git push -f --set-upstream origin $latest_release
       - name: Install build dependencies
         run: |
          sudo apt update
          sudo apt-get install -y osc
          osc --help
       - name: Set up OSC credentials
         run: mkdir -p ~/.config/osc; touch ~/.config/osc/oscrc; echo "${{ secrets.OSCRC }}" > ~/.config/osc/oscrc
       - name: Trigger Build
         run:  |
          osc -A https://api.opensuse.org checkout home:sounddrill/Crave && cd $_  
          mv ${{ github.workspace }}/* . -f || true
          rm -rf .git
          osc add *
          osc ci -m "Version bump to $latest_release"
