on:
 schedule:
    - cron: '0 0 * * *' # This runs daily at midnight

jobs:
 update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Check for new Floorp releases
        id: check_release
        run: |
          python -c "
import requests

def get_latest_release(repo):
    response = requests.get(f'https://api.github.com/repos/{repo}/releases/latest')
    if response.status_code == 200:
        return response.json()['tag_name']
    return None

latest_release = get_latest_release('Floorp-Projects/Floorp')
if latest_release:
    print(f'::set-output name=latest_release::{latest_release}')
"

      - name: Update _service and floorp-brower-nosrc.spec
        if: steps.check_release.outputs.latest_release != ''
        run: |
          # Replace the placeholder with the actual logic to update the files
          echo "Updating _service and floorp-brower-nosrc.spec with the new release URL"
          # You might need to use a script or a tool to update the files based on the latest release

      - name: Commit and push changes
        if: steps.check_release.outputs.latest_release != ''
        run: |
          git config --global user.name 'sounddrill31'
          git config --global user.email 'sounddrill31@gmail.com'
          git add .
          git commit -m "Update Floorp browser to latest release"
          git push
